# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ feature/#14_prepare_0.0.2 ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      - name: Install texlive
        shell: bash
        run: |
          sudo apt install -y texlive texlive-latex-extra
        # Render documentation to HTML format
      - name: Generate HTML/PDF
        shell: bash
        run: |
          ls -l ${{github.workspace}}
          python -m venv ./${{github.workspace}}/user_guide/venv
          source ./${{github.workspace}}/user_guide/venv/bin/activate
          pip install -r ${{github.workspace}}/user_guide/requirements.txt
          conan install ${{github.workspace}}/user_guide -if ${{github.workspace}}/user_guide/build -o generate_pdf=True
          conan build ${{github.workspace}}/user_guide -bf ${{github.workspace}}/user_guide/build

      # Upload Artifacts (HTML and PDF)
      - name: Upload Artifacts (HTML and PDF)
        uses: actions/upload-artifact@v1
        with:
          name: Artifacts
          path: ${{github.workspace}}/user_guide/build/*.zip